---
name: ci
# yamllint disable-line rule:truthy
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: Setup enviroment
        run: pip install ruff 
      - name: Check style
        run: ruff format --diff .
      - name: Lint - ruff
        run: ruff check .
